-- MySQL Script generated by MySQL Workbench
-- Sat Jan 27 18:40:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biletarnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biletarnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biletarnica` DEFAULT CHARACTER SET utf8 ;
USE `biletarnica` ;

-- -----------------------------------------------------
-- Table `biletarnica`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  INDEX `fk_Korisnik_Role_idx` (`Role_idRole` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_Role`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `biletarnica`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Grad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Grad` (
  `idGrad` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Venue` (
  `idVenue` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `Grad_idGrad` INT NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  PRIMARY KEY (`idVenue`),
  INDEX `fk_Venue_Grad1_idx` (`Grad_idGrad` ASC) VISIBLE,
  INDEX `fk_Venue_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Venue_Grad1`
    FOREIGN KEY (`Grad_idGrad`)
    REFERENCES `biletarnica`.`Grad` (`idGrad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venue_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `biletarnica`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`TipDogadjaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`TipDogadjaja` (
  `idTipDogadjaja` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idTipDogadjaja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Dogadjaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Dogadjaj` (
  `idDogadjaj` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(100) NOT NULL,
  `datum` DATETIME NOT NULL,
  `opis` VARCHAR(500) NULL,
  `Venue_idVenue` INT NOT NULL,
  `TipDogadjaja_idTipDogadjaja` INT NOT NULL,
  PRIMARY KEY (`idDogadjaj`),
  INDEX `fk_Dogadjaj_Venue1_idx` (`Venue_idVenue` ASC) VISIBLE,
  INDEX `fk_Dogadjaj_TipDogadjaja1_idx` (`TipDogadjaja_idTipDogadjaja` ASC) VISIBLE,
  CONSTRAINT `fk_Dogadjaj_Venue1`
    FOREIGN KEY (`Venue_idVenue`)
    REFERENCES `biletarnica`.`Venue` (`idVenue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dogadjaj_TipDogadjaja1`
    FOREIGN KEY (`TipDogadjaja_idTipDogadjaja`)
    REFERENCES `biletarnica`.`TipDogadjaja` (`idTipDogadjaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`TipSedista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`TipSedista` (
  `idTipSedista` INT NOT NULL AUTO_INCREMENT,
  `kategorija` VARCHAR(45) NOT NULL,
  `cena` INT NOT NULL,
  `raspolozivost` INT NOT NULL,
  `Dogadjaj_idDogadjaj` INT NOT NULL,
  PRIMARY KEY (`idTipSedista`),
  INDEX `fk_TipSedista_Dogadjaj1_idx` (`Dogadjaj_idDogadjaj` ASC) VISIBLE,
  CONSTRAINT `fk_TipSedista_Dogadjaj1`
    FOREIGN KEY (`Dogadjaj_idDogadjaj`)
    REFERENCES `biletarnica`.`Dogadjaj` (`idDogadjaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Sediste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Sediste` (
  `idSediste` INT NOT NULL AUTO_INCREMENT,
  `red` INT NULL,
  `broj` INT NULL,
  `TipSedista_idTipSedista` INT NOT NULL,
  PRIMARY KEY (`idSediste`),
  INDEX `fk_Sediste_TipSedista1_idx` (`TipSedista_idTipSedista` ASC) VISIBLE,
  CONSTRAINT `fk_Sediste_TipSedista1`
    FOREIGN KEY (`TipSedista_idTipSedista`)
    REFERENCES `biletarnica`.`TipSedista` (`idTipSedista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biletarnica`.`Karta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biletarnica`.`Karta` (
  `idKarta` INT NOT NULL AUTO_INCREMENT,
  `datumProdaje` DATE NOT NULL,
  `Korisnik_idKorisnik` INT NOT NULL,
  `Dogadjaj_idDogadjaj` INT NOT NULL,
  `Sediste_idSediste` INT NOT NULL,
  PRIMARY KEY (`idKarta`),
  INDEX `fk_Karta_Korisnik1_idx` (`Korisnik_idKorisnik` ASC) VISIBLE,
  INDEX `fk_Karta_Dogadjaj1_idx` (`Dogadjaj_idDogadjaj` ASC) VISIBLE,
  INDEX `fk_Karta_Sediste1_idx` (`Sediste_idSediste` ASC) VISIBLE,
  CONSTRAINT `fk_Karta_Korisnik1`
    FOREIGN KEY (`Korisnik_idKorisnik`)
    REFERENCES `biletarnica`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Karta_Dogadjaj1`
    FOREIGN KEY (`Dogadjaj_idDogadjaj`)
    REFERENCES `biletarnica`.`Dogadjaj` (`idDogadjaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Karta_Sediste1`
    FOREIGN KEY (`Sediste_idSediste`)
    REFERENCES `biletarnica`.`Sediste` (`idSediste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
